[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/dev"
desc = "Cd to ~/dev"

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/dox"
desc = "Cd to ~/dox"

[[mgr.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/dl"
desc = "Cd to ~/dl"

[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/pix"
desc = "Cd to ~/pix"

[[mgr.prepend_keymap]]
on = ["g", "s"]
run = "cd ~/scripts"
desc = "Cd to ~/scripts"

[[mgr.prepend_keymap]]
on = ["g", "t"]
run = "cd ~/temp"
desc = "Cd to ~/temp"

[[mgr.prepend_keymap]]
on = "<C-n>"
run = 'shell -- dragon-drop --and-exit "$@"'
# run = 'shell -- dragon -x -a -T "$@"'
